/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.web.mvc.model.entity;

public class ModuleModel {
   public String getModuleName() {
      return null;
   }
}
