/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.codegen.model;

public class Constants {

   public static final String ATTR_KEY = "key";

   public static final String ATTR_MODE = "mode";

   public static final String ATTR_NAME = "name";

   public static final String ATTR_NO_NAMESPACE = "no-namespace";

   public static final String ATTR_OP = "op";

   public static final String ATTR_PATH = "path";

   public static final String ATTR_TEMPLATE = "template";

   public static final String ELEMENT_TEXT = "text";

   public static final String ENTITY_CODEGEN = "codegen";

   public static final String ENTITY_FILE = "file";

   public static final String ENTITY_MANIFEST = "manifest";

   public static final String ENTITY_NODE = "node";

   public static final String ENTITY_OUTPUT = "output";

   public static final String ENTITY_OUTPUTS = "outputs";

   public static final String ENTITY_PROPERTY = "property";

   public static final String ENTITY_STRUCTURE = "structure";

   public static final String ENTITY_FILES = "files";

   public static final String ENTITY_NODES = "nodes";

   public static final String ENTITY_PROPERTIES = "properties";
}
