/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.codegen.model;

import org.unidal.codegen.model.entity.Any;
import org.unidal.codegen.model.entity.CodegenModel;
import org.unidal.codegen.model.entity.FileModel;
import org.unidal.codegen.model.entity.ManifestModel;
import org.unidal.codegen.model.entity.NodeModel;
import org.unidal.codegen.model.entity.OutputModel;
import org.unidal.codegen.model.entity.OutputsModel;
import org.unidal.codegen.model.entity.PropertyModel;
import org.unidal.codegen.model.entity.StructureModel;

public interface IVisitor {

   public void visitAny(Any any);

   public void visitCodegen(CodegenModel codegen);

   public void visitFile(FileModel file);

   public void visitManifest(ManifestModel manifest);

   public void visitNode(NodeModel node);

   public void visitOutput(OutputModel output);

   public void visitOutputs(OutputsModel outputs);

   public void visitProperty(PropertyModel property);

   public void visitStructure(StructureModel structure);
}
