/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.maven.plugin.source.count.entity;

import org.unidal.maven.plugin.source.count.BaseEntity;
import org.unidal.maven.plugin.source.count.IVisitor;

public class CountModel extends BaseEntity<CountModel> {
   private int m_lines;

   private int m_empty;

   private int m_comment;

   public CountModel() {
   }

   @Override
   public void accept(IVisitor visitor) {
      visitor.visitCount(this);
   }

   @Override
   public boolean equals(Object obj) {
      if (obj instanceof CountModel) {
         CountModel _o = (CountModel) obj;

         if (getLines() != _o.getLines()) {
            return false;
         }

         if (getEmpty() != _o.getEmpty()) {
            return false;
         }

         if (getComment() != _o.getComment()) {
            return false;
         }


         return true;
      }

      return false;
   }

   public int getComment() {
      return m_comment;
   }

   public int getEmpty() {
      return m_empty;
   }

   public int getLines() {
      return m_lines;
   }

   @Override
   public int hashCode() {
      int hash = 0;

      hash = hash * 31 + m_lines;
      hash = hash * 31 + m_empty;
      hash = hash * 31 + m_comment;

      return hash;
   }

   public CountModel incComment() {
      m_comment++;
      return this;
   }

   public CountModel incComment(int comment) {
      m_comment += comment;
      return this;
   }

   public CountModel incEmpty() {
      m_empty++;
      return this;
   }

   public CountModel incEmpty(int empty) {
      m_empty += empty;
      return this;
   }

   public CountModel incLines() {
      m_lines++;
      return this;
   }

   public CountModel incLines(int lines) {
      m_lines += lines;
      return this;
   }

   @Override
   public void mergeAttributes(CountModel other) {
      m_lines = other.getLines();

      m_empty = other.getEmpty();

      m_comment = other.getComment();
   }

   public CountModel setComment(int comment) {
      m_comment = comment;
      return this;
   }

   public CountModel setEmpty(int empty) {
      m_empty = empty;
      return this;
   }

   public CountModel setLines(int lines) {
      m_lines = lines;
      return this;
   }

   /********* Code Snippet Start *********/
   public void add(CountModel count) {
      m_lines += count.m_lines;
      m_empty += count.m_empty;
      m_comment += count.m_comment;
   }

   /********* Code Snippet End *********/
}
