/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.maven.plugins.source.model;

import org.unidal.maven.plugins.source.model.entity.ClassModel;
import org.unidal.maven.plugins.source.model.entity.CountModel;
import org.unidal.maven.plugins.source.model.entity.ProjectModel;
import org.unidal.maven.plugins.source.model.entity.RootModel;

public interface IVisitor {

   public void visitClass(ClassModel _class);

   public void visitCount(CountModel count);

   public void visitProject(ProjectModel project);

   public void visitRoot(RootModel root);
}
