/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.codegen.model.transform;

import java.util.ArrayList;
import java.util.List;
import org.unidal.codegen.model.entity.CodegenModel;
import org.unidal.codegen.model.entity.FileModel;
import org.unidal.codegen.model.entity.ManifestModel;
import org.unidal.codegen.model.entity.NodeModel;
import org.unidal.codegen.model.entity.OutputModel;
import org.unidal.codegen.model.entity.OutputsModel;
import org.unidal.codegen.model.entity.PropertyModel;
import org.unidal.codegen.model.entity.StructureModel;

public class DefaultLinker {
   @SuppressWarnings("unused")
   private boolean m_deferrable;

   private List<Runnable> m_deferedJobs = new ArrayList<Runnable>();

   public DefaultLinker(boolean deferrable) {
      m_deferrable = deferrable;
   }

   public void finish() {
      for (Runnable job : m_deferedJobs) {
         job.run();
      }
   }

   public boolean onFile(final ManifestModel parent, final FileModel file) {
      parent.addFile(file);
      return true;
   }

   public boolean onManifest(final CodegenModel parent, final ManifestModel manifest) {
      parent.setManifest(manifest);
      return true;
   }

   public boolean onNode(final StructureModel parent, final NodeModel node) {
      parent.setNode(node);
      return true;
   }

   public boolean onNode(final NodeModel parent, final NodeModel node) {
      parent.addNode(node);
      return true;
   }

   public boolean onOutput(final OutputsModel parent, final OutputModel output) {
      parent.addOutput(output);
      return true;
   }

   public boolean onOutputs(final CodegenModel parent, final OutputsModel outputs) {
      parent.setOutputs(outputs);
      return true;
   }

   public boolean onProperty(final OutputModel parent, final PropertyModel property) {
      parent.addProperty(property);
      return true;
   }

   public boolean onStructure(final CodegenModel parent, final StructureModel structure) {
      parent.setStructure(structure);
      return true;
   }
}
