/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.maven.plugin.source.count;

public class Constants {

   public static final String ATTR_CLASS = "class";

   public static final String ATTR_COMMENT = "comment";

   public static final String ATTR_EMPTY = "empty";

   public static final String ATTR_GENERATED = "generated";

   public static final String ATTR_LINES = "lines";

   public static final String ATTR_NAME = "name";

   public static final String ATTR_PACKAGE = "package";

   public static final String ATTR_TEST = "test";

   public static final String ENTITY_CLASS = "class";

   public static final String ENTITY_COUNT = "count";

   public static final String ENTITY_PROJECT = "project";

   public static final String ENTITY_ROOT = "root";

   public static final String ENTITY_CLASSES = "classes";

   public static final String ENTITY_PROJECTS = "projects";
}
