/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.maven.plugin.wizard.model.transform;

import java.util.ArrayList;
import java.util.List;
import org.unidal.maven.plugin.wizard.model.entity.Datasource;
import org.unidal.maven.plugin.wizard.model.entity.File;
import org.unidal.maven.plugin.wizard.model.entity.Group;
import org.unidal.maven.plugin.wizard.model.entity.Jdbc;
import org.unidal.maven.plugin.wizard.model.entity.Manifest;
import org.unidal.maven.plugin.wizard.model.entity.Model;
import org.unidal.maven.plugin.wizard.model.entity.Module;
import org.unidal.maven.plugin.wizard.model.entity.Page;
import org.unidal.maven.plugin.wizard.model.entity.Table;
import org.unidal.maven.plugin.wizard.model.entity.Webapp;
import org.unidal.maven.plugin.wizard.model.entity.Wizard;

public class DefaultLinker {
   @SuppressWarnings("unused")
   private boolean m_deferrable;

   private List<Runnable> m_deferedJobs = new ArrayList<Runnable>();

   public DefaultLinker(boolean deferrable) {
      m_deferrable = deferrable;
   }

   public void finish() {
      for (Runnable job : m_deferedJobs) {
         job.run();
      }
   }

   public boolean onDatasource(final Jdbc parent, final Datasource datasource) {
      parent.setDatasource(datasource);
      return true;
   }

   public boolean onFile(final Manifest parent, final File file) {
      parent.addFile(file);
      return true;
   }

   public boolean onGroup(final Jdbc parent, final Group group) {
      parent.addGroup(group);
      return true;
   }

   public boolean onJdbc(final Wizard parent, final Jdbc jdbc) {
      parent.addJdbc(jdbc);
      return true;
   }

   public boolean onManifest(final Wizard parent, final Manifest manifest) {
      parent.setManifest(manifest);
      return true;
   }

   public boolean onModel(final Wizard parent, final Model model) {
      parent.addModel(model);
      return true;
   }

   public boolean onModule(final Webapp parent, final Module module) {
      parent.addModule(module);
      return true;
   }

   public boolean onPage(final Module parent, final Page page) {
      parent.addPage(page);
      return true;
   }

   public boolean onTable(final Group parent, final Table table) {
      parent.addTable(table);
      return true;
   }

   public boolean onWebapp(final Wizard parent, final Webapp webapp) {
      parent.setWebapp(webapp);
      return true;
   }
}
