/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.codegen.model.entity;

import java.util.ArrayList;
import java.util.List;

import org.unidal.codegen.model.BaseEntity;
import org.unidal.codegen.model.IVisitor;

public class ManifestModel extends BaseEntity<ManifestModel> {
   private String m_path;

   private List<FileModel> m_files = new ArrayList<FileModel>();

   public ManifestModel() {
   }

   @Override
   public void accept(IVisitor visitor) {
      visitor.visitManifest(this);
   }

   public ManifestModel addFile(FileModel file) {
      m_files.add(file);
      return this;
   }

   @Override
   public boolean equals(Object obj) {
      if (obj instanceof ManifestModel) {
         ManifestModel _o = (ManifestModel) obj;

         if (!equals(getPath(), _o.getPath())) {
            return false;
         }

         if (!equals(getFiles(), _o.getFiles())) {
            return false;
         }


         return true;
      }

      return false;
   }

   public List<FileModel> getFiles() {
      return m_files;
   }

   public String getPath() {
      return m_path;
   }

   @Override
   public int hashCode() {
      int hash = 0;

      hash = hash * 31 + (m_path == null ? 0 : m_path.hashCode());
      for (FileModel e : m_files) {
         hash = hash * 31 + (e == null ? 0 :e.hashCode());
      }


      return hash;
   }

   @Override
   public void mergeAttributes(ManifestModel other) {
      if (other.getPath() != null) {
         m_path = other.getPath();
      }
   }

   public ManifestModel setPath(String path) {
      m_path = path;
      return this;
   }

}
