/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.codegen.model.entity;

import static org.unidal.codegen.model.Constants.ATTR_NAME;
import static org.unidal.codegen.model.Constants.ENTITY_PROPERTY;

import org.unidal.codegen.model.BaseEntity;
import org.unidal.codegen.model.IVisitor;

public class PropertyModel extends BaseEntity<PropertyModel> {
   private String m_name;

   private String m_text;

   public PropertyModel() {
   }

   public PropertyModel(String name) {
      m_name = name;
   }

   @Override
   public void accept(IVisitor visitor) {
      visitor.visitProperty(this);
   }

   @Override
   public boolean equals(Object obj) {
      if (obj instanceof PropertyModel) {
         PropertyModel _o = (PropertyModel) obj;

         if (!equals(getName(), _o.getName())) {
            return false;
         }

         return true;
      }

      return false;
   }

   public String getName() {
      return m_name;
   }

   public String getText() {
      return m_text;
   }

   @Override
   public int hashCode() {
      int hash = 0;

      hash = hash * 31 + (m_name == null ? 0 : m_name.hashCode());

      return hash;
   }

   @Override
   public void mergeAttributes(PropertyModel other) {
      assertAttributeEquals(other, ENTITY_PROPERTY, ATTR_NAME, m_name, other.getName());

   }

   public PropertyModel setName(String name) {
      m_name = name;
      return this;
   }

   public PropertyModel setText(String text) {
      m_text = text;
      return this;
   }

}
