/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.maven.plugin.source.lines.entity;

import static org.unidal.maven.plugin.source.lines.Constants.ATTR_PACKAGE;
import static org.unidal.maven.plugin.source.lines.Constants.ATTR_CLASS;
import static org.unidal.maven.plugin.source.lines.Constants.ENTITY_CLASS;

import org.unidal.maven.plugin.source.lines.BaseEntity;
import org.unidal.maven.plugin.source.lines.IVisitor;

public class ClassModel extends BaseEntity<ClassModel> {
   private String m_package;

   private String m_class;

   private Boolean m_generated;

   private Boolean m_test;

   private CountModel m_count;

   public ClassModel() {
   }

   public ClassModel(String _package, String _class) {
      m_package = _package;
      m_class = _class;
   }

   @Override
   public void accept(IVisitor visitor) {
      visitor.visitClass(this);
   }

   @Override
   public boolean equals(Object obj) {
      if (obj instanceof ClassModel) {
         ClassModel _o = (ClassModel) obj;

         if (!equals(getPackage(), _o.getPackage())) {
            return false;
         }

         if (!equals(getClazz(), _o.getClazz())) {
            return false;
         }

         return true;
      }

      return false;
   }

   public String getClazz() {
      return m_class;
   }

   public CountModel getCount() {
      return m_count;
   }

   public Boolean getGenerated() {
      return m_generated;
   }

   public String getPackage() {
      return m_package;
   }

   public Boolean getTest() {
      return m_test;
   }

   @Override
   public int hashCode() {
      int hash = 0;

      hash = hash * 31 + (m_package == null ? 0 : m_package.hashCode());
      hash = hash * 31 + (m_class == null ? 0 : m_class.hashCode());

      return hash;
   }

   public boolean isGenerated() {
      return m_generated != null && m_generated.booleanValue();
   }

   public boolean isTest() {
      return m_test != null && m_test.booleanValue();
   }

   @Override
   public void mergeAttributes(ClassModel other) {
      assertAttributeEquals(other, ENTITY_CLASS, ATTR_PACKAGE, m_package, other.getPackage());
      assertAttributeEquals(other, ENTITY_CLASS, ATTR_CLASS, m_class, other.getClazz());

      if (other.getGenerated() != null) {
         m_generated = other.getGenerated();
      }

      if (other.getTest() != null) {
         m_test = other.getTest();
      }
   }

   public ClassModel setClazz(String _class) {
      m_class = _class;
      return this;
   }

   public ClassModel setCount(CountModel count) {
      m_count = count;
      return this;
   }

   public ClassModel setGenerated(Boolean generated) {
      m_generated = generated;
      return this;
   }

   public ClassModel setPackage(String _package) {
      m_package = _package;
      return this;
   }

   public ClassModel setTest(Boolean test) {
      m_test = test;
      return this;
   }

}
