/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.maven.plugin.source.lines.transform;

import java.util.ArrayList;
import java.util.List;
import org.unidal.maven.plugin.source.lines.entity.ClassModel;
import org.unidal.maven.plugin.source.lines.entity.CountModel;
import org.unidal.maven.plugin.source.lines.entity.ProjectModel;
import org.unidal.maven.plugin.source.lines.entity.RootModel;

public class DefaultLinker {
   @SuppressWarnings("unused")
   private boolean m_deferrable;

   private List<Runnable> m_deferedJobs = new ArrayList<Runnable>();

   public DefaultLinker(boolean deferrable) {
      m_deferrable = deferrable;
   }

   public void finish() {
      for (Runnable job : m_deferedJobs) {
         job.run();
      }
   }

   public boolean onClass(final ProjectModel parent, final ClassModel _class) {
      parent.addClass(_class);
      return true;
   }

   public boolean onCount(final RootModel parent, final CountModel count) {
      parent.setCount(count);
      return true;
   }

   public boolean onCount(final ProjectModel parent, final CountModel count) {
      parent.setCount(count);
      return true;
   }

   public boolean onCount(final ClassModel parent, final CountModel count) {
      parent.setCount(count);
      return true;
   }

   public boolean onProject(final RootModel parent, final ProjectModel project) {
      parent.addProject(project);
      return true;
   }
}
