/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.maven.plugins.source.model.transform;

import org.unidal.maven.plugins.source.model.entity.ClassModel;
import org.unidal.maven.plugins.source.model.entity.CountModel;
import org.unidal.maven.plugins.source.model.entity.ProjectModel;
import org.unidal.maven.plugins.source.model.entity.RootModel;

public interface IParser<T> {
   public RootModel parse(IMaker<T> maker, ILinker linker, T node);

   public void parseForClassModel(IMaker<T> maker, ILinker linker, ClassModel parent, T node);

   public void parseForCountModel(IMaker<T> maker, ILinker linker, CountModel parent, T node);

   public void parseForProjectModel(IMaker<T> maker, ILinker linker, ProjectModel parent, T node);
}
