/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.maven.plugins.source.model.transform;

import org.unidal.maven.plugins.source.model.entity.ClassModel;
import org.unidal.maven.plugins.source.model.entity.CountModel;
import org.unidal.maven.plugins.source.model.entity.ProjectModel;
import org.unidal.maven.plugins.source.model.entity.RootModel;

public interface ILinker {

   public boolean onClass(ProjectModel parent, ClassModel _class);

   public boolean onCount(RootModel parent, CountModel count);

   public boolean onCount(ProjectModel parent, CountModel count);

   public boolean onCount(ClassModel parent, CountModel count);

   public boolean onProject(RootModel parent, ProjectModel project);
}
