/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.maven.plugin.wizard.model.entity;

import java.util.ArrayList;
import java.util.List;

import org.unidal.maven.plugin.wizard.model.BaseEntity;
import org.unidal.maven.plugin.wizard.model.IVisitor;

public class Manifest extends BaseEntity<Manifest> {
   private List<File> m_files = new ArrayList<File>();

   public Manifest() {
   }

   @Override
   public void accept(IVisitor visitor) {
      visitor.visitManifest(this);
   }

   public Manifest addFile(File file) {
      m_files.add(file);
      return this;
   }

   @Override
   public boolean equals(Object obj) {
      if (obj instanceof Manifest) {
         Manifest _o = (Manifest) obj;

         if (!equals(getFiles(), _o.getFiles())) {
            return false;
         }


         return true;
      }

      return false;
   }

   public List<File> getFiles() {
      return m_files;
   }

   @Override
   public int hashCode() {
      int hash = 0;

      for (File e : m_files) {
         hash = hash * 31 + (e == null ? 0 :e.hashCode());
      }


      return hash;
   }

   @Override
   public void mergeAttributes(Manifest other) {
   }

}
