/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.maven.plugins.source.model.entity;

import org.unidal.maven.plugins.source.model.BaseEntity;
import org.unidal.maven.plugins.source.model.IVisitor;

public class ClassModel extends BaseEntity<ClassModel> {
   private String m_package;

   private String m_class;

   private Boolean m_main;

   private Boolean m_codegen;

   private Boolean m_test;

   private CountModel m_count;

   public ClassModel() {
   }

   @Override
   public void accept(IVisitor visitor) {
      visitor.visitClass(this);
   }

   @Override
   public boolean equals(Object obj) {
      if (obj instanceof ClassModel) {
         ClassModel _o = (ClassModel) obj;

         if (!equals(getPackage(), _o.getPackage())) {
            return false;
         }

         if (!equals(getClazz(), _o.getClazz())) {
            return false;
         }

         if (!equals(getMain(), _o.getMain())) {
            return false;
         }

         if (!equals(getCodegen(), _o.getCodegen())) {
            return false;
         }

         if (!equals(getTest(), _o.getTest())) {
            return false;
         }

         if (!equals(getCount(), _o.getCount())) {
            return false;
         }


         return true;
      }

      return false;
   }

   public String getClazz() {
      return m_class;
   }

   public Boolean getCodegen() {
      return m_codegen;
   }

   public CountModel getCount() {
      return m_count;
   }

   public Boolean getMain() {
      return m_main;
   }

   public String getPackage() {
      return m_package;
   }

   public Boolean getTest() {
      return m_test;
   }

   @Override
   public int hashCode() {
      int hash = 0;

      hash = hash * 31 + (m_package == null ? 0 : m_package.hashCode());
      hash = hash * 31 + (m_class == null ? 0 : m_class.hashCode());
      hash = hash * 31 + (m_main == null ? 0 : m_main.hashCode());
      hash = hash * 31 + (m_codegen == null ? 0 : m_codegen.hashCode());
      hash = hash * 31 + (m_test == null ? 0 : m_test.hashCode());
      hash = hash * 31 + (m_count == null ? 0 : m_count.hashCode());

      return hash;
   }

   public boolean isCodegen() {
      return m_codegen != null && m_codegen.booleanValue();
   }

   public boolean isMain() {
      return m_main != null && m_main.booleanValue();
   }

   public boolean isTest() {
      return m_test != null && m_test.booleanValue();
   }

   @Override
   public void mergeAttributes(ClassModel other) {
      if (other.getPackage() != null) {
         m_package = other.getPackage();
      }

      if (other.getClazz() != null) {
         m_class = other.getClazz();
      }

      if (other.getMain() != null) {
         m_main = other.getMain();
      }

      if (other.getCodegen() != null) {
         m_codegen = other.getCodegen();
      }

      if (other.getTest() != null) {
         m_test = other.getTest();
      }
   }

   public ClassModel setClazz(String _class) {
      m_class = _class;
      return this;
   }

   public ClassModel setCodegen(Boolean codegen) {
      m_codegen = codegen;
      return this;
   }

   public ClassModel setCount(CountModel count) {
      m_count = count;
      return this;
   }

   public ClassModel setMain(Boolean main) {
      m_main = main;
      return this;
   }

   public ClassModel setPackage(String _package) {
      m_package = _package;
      return this;
   }

   public ClassModel setTest(Boolean test) {
      m_test = test;
      return this;
   }

}
