/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.maven.plugins.source.model.entity;

import java.util.ArrayList;
import java.util.List;

import org.unidal.maven.plugins.source.model.BaseEntity;
import org.unidal.maven.plugins.source.model.IVisitor;

public class RootModel extends BaseEntity<RootModel> {
   private CountModel m_count;

   private List<ProjectModel> m_projects = new ArrayList<ProjectModel>();

   public RootModel() {
   }

   @Override
   public void accept(IVisitor visitor) {
      visitor.visitRoot(this);
   }

   public RootModel addProject(ProjectModel project) {
      m_projects.add(project);
      return this;
   }

   @Override
   public boolean equals(Object obj) {
      if (obj instanceof RootModel) {
         RootModel _o = (RootModel) obj;

         if (!equals(getCount(), _o.getCount())) {
            return false;
         }

         if (!equals(getProjects(), _o.getProjects())) {
            return false;
         }


         return true;
      }

      return false;
   }

   public CountModel getCount() {
      return m_count;
   }

   public List<ProjectModel> getProjects() {
      return m_projects;
   }

   @Override
   public int hashCode() {
      int hash = 0;

      hash = hash * 31 + (m_count == null ? 0 : m_count.hashCode());
      for (ProjectModel e : m_projects) {
         hash = hash * 31 + (e == null ? 0 :e.hashCode());
      }


      return hash;
   }

   @Override
   public void mergeAttributes(RootModel other) {
   }

   public RootModel setCount(CountModel count) {
      m_count = count;
      return this;
   }

}
