/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.maven.plugins.source.model.entity;

import java.util.ArrayList;
import java.util.List;

import org.unidal.maven.plugins.source.model.BaseEntity;
import org.unidal.maven.plugins.source.model.IVisitor;

public class ProjectModel extends BaseEntity<ProjectModel> {
   private String m_name;

   private CountModel m_count;

   private List<ClassModel> m_classes = new ArrayList<ClassModel>();

   public ProjectModel() {
   }

   @Override
   public void accept(IVisitor visitor) {
      visitor.visitProject(this);
   }

   public ProjectModel addClass(ClassModel _class) {
      m_classes.add(_class);
      return this;
   }

   @Override
   public boolean equals(Object obj) {
      if (obj instanceof ProjectModel) {
         ProjectModel _o = (ProjectModel) obj;

         if (!equals(getName(), _o.getName())) {
            return false;
         }

         if (!equals(getCount(), _o.getCount())) {
            return false;
         }

         if (!equals(getClasses(), _o.getClasses())) {
            return false;
         }


         return true;
      }

      return false;
   }

   public List<ClassModel> getClasses() {
      return m_classes;
   }

   public CountModel getCount() {
      return m_count;
   }

   public String getName() {
      return m_name;
   }

   @Override
   public int hashCode() {
      int hash = 0;

      hash = hash * 31 + (m_name == null ? 0 : m_name.hashCode());
      hash = hash * 31 + (m_count == null ? 0 : m_count.hashCode());
      for (ClassModel e : m_classes) {
         hash = hash * 31 + (e == null ? 0 :e.hashCode());
      }


      return hash;
   }

   @Override
   public void mergeAttributes(ProjectModel other) {
      if (other.getName() != null) {
         m_name = other.getName();
      }
   }

   public ProjectModel setCount(CountModel count) {
      m_count = count;
      return this;
   }

   public ProjectModel setName(String name) {
      m_name = name;
      return this;
   }

}
